name: Sync hf-spaces with dev

on:
  push:
    branches:
      - dev
      - hf-spaces
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync with dev
        run: |
          git checkout dev
          git fetch origin
          git checkout hf-space
          git pull
          git merge origin/dev
          git push origin hf-space
